/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_com_calculator_util_NativeCalculator */

#ifndef _Included_demo_com_calculator_util_NativeCalculator
#define _Included_demo_com_calculator_util_NativeCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_com_calculator_util_NativeCalculator
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_demo_com_calculator_util_NativeCalculator_addAndModulo7
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     demo_com_calculator_util_NativeCalculator
 * Method:    subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_demo_com_calculator_util_NativeCalculator_subtractAndModulo7
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     demo_com_calculator_util_NativeCalculator
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_demo_com_calculator_util_NativeCalculator_multiplyAndModulo7
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
